const $=id=>document.getElementById(id);const displayEl=$('display'),expressionEl=$('expression'),historyEl=$('history'),settingsModal=$('settingsModal'),scientificEl=$('scientific'),toastEl=$('toast');
let current='0',previous=null,operator=null,waiting=false,expression='',memory=Number(localStorage.getItem('aitherCalculatorMemory')||0),angle=localStorage.getItem('aitherCalculatorAngle')||'DEG',ans=Number(localStorage.getItem('aitherCalculatorAns')||0);
let history=JSON.parse(localStorage.getItem('aitherCalculatorHistory')||'[]');
const settings=Object.assign({scientific:false,dark:true,haptic:true,sound:false,autoCopy:false},JSON.parse(localStorage.getItem('aitherCalculatorSettings')||'{}'));
function save(){localStorage.setItem('aitherCalculatorHistory',JSON.stringify(history));localStorage.setItem('aitherCalculatorSettings',JSON.stringify(settings));localStorage.setItem('aitherCalculatorMemory',String(memory));localStorage.setItem('aitherCalculatorAngle',angle);localStorage.setItem('aitherCalculatorAns',String(ans))}
function vibrate(){if(settings.haptic&&navigator.vibrate)navigator.vibrate(8)}function beep(){if(!settings.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=520;g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.045)}catch(e){}}function feedback(){vibrate();beep()}
function round(n){return Number.parseFloat(Number(n).toPrecision(12))}function format(n){return Number(n).toLocaleString('en-US',{maximumFractionDigits:10})}function render(){displayEl.textContent=current;expressionEl.textContent=expression;renderHistory()}
function inputNumber(n){feedback();if(current==='Error'||waiting){current=n;waiting=false}else current=current==='0'?n:current+n;render()}function decimal(){feedback();if(current==='Error'||waiting){current='0.';waiting=false}else if(!current.includes('.'))current+='.';render()}function clear(){feedback();current='0';previous=null;operator=null;waiting=false;expression='';render()}function backspace(){feedback();if(waiting||current==='Error')return;current=current.length>1?current.slice(0,-1):'0';render()}
function setOperator(op){feedback();if(current==='Error')return;if(previous!==null&&operator&&!waiting)calculate(false);previous=Number(current);operator=op;waiting=true;expression=`${format(previous)} ${op}`;render()}
function calculate(record=true){if(previous===null||!operator)return;const a=previous,b=Number(current);let result;switch(operator){case'+':result=a+b;break;case'−':result=a-b;break;case'×':result=a*b;break;case'÷':result=b===0?NaN:a/b;break;case'^':result=a**b;break}const shown=`${format(a)} ${operator} ${format(b)}`;current=Number.isFinite(result)?String(round(result)):'Error';if(record){history.unshift({expression:shown,result:current,time:Date.now()});history=history.slice(0,100);if(Number.isFinite(result))ans=round(result);save();if(settings.autoCopy)copyResult()}previous=null;operator=null;waiting=true;expression=shown;render();feedback()}
function percent(){feedback();const n=Number(current);current=Number.isFinite(n)?String(round(n/100)):'Error';render()}function sign(){feedback();if(current!=='Error')current=String(-Number(current));render()}
function scientific(fn){feedback();const n=Number(current),rads=angle==='DEG'?n*Math.PI/180:n;let r;switch(fn){case'sin':r=Math.sin(rads);break;case'cos':r=Math.cos(rads);break;case'tan':r=Math.tan(rads);break;case'sqrt':r=Math.sqrt(n);break;case'square':r=n*n;break;case'cube':r=n*n*n;break;case'log':r=Math.log10(n);break;case'ln':r=Math.log(n);break;case'abs':r=Math.abs(n);break;case'fact':r=n>=0&&Number.isInteger(n)&&n<=170?factorial(n):NaN;break}current=Number.isFinite(r)?String(round(r)):'Error';expression=`${fn}(${format(n)})`;history.unshift({expression,result:current,time:Date.now()});history=history.slice(0,100);if(Number.isFinite(r))ans=round(r);save();render()}function factorial(n){let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function constant(name){feedback();current=name==='pi'?String(Math.PI):name==='e'?String(Math.E):String(ans);waiting=false;expression=name==='pi'?'π':name==='e'?'e':'Ans';render()}
function parenthesis(){feedback();expression+='(';showToast('Parentheses are supported in the expression display; use a complete expression in v3');render()}
function memoryAction(a){feedback();const n=Number(current);if(a==='MC')memory=0;else if(a==='MR'){current=String(round(memory));waiting=false}else if(a==='M+')memory+=n;else if(a==='M−')memory-=n;save();showToast(`Memory: ${format(memory)}`);render()}
function renderHistory(){if(!history.length){historyEl.className='history-empty';historyEl.textContent='Your calculations will appear here.';return}historyEl.className='history';historyEl.innerHTML=history.map((x,i)=>`<div class="history-item" data-history="${i}"><div><span class="history-expression">${escapeHtml(x.expression)}</span><span class="history-time">${x.time?new Date(x.time).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):''}</span></div><div class="history-result">${escapeHtml(x.result)}</div></div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function showToast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toastEl.classList.remove('show'),1800)}
async function copyResult(){try{await navigator.clipboard.writeText(current);showToast('Result copied')}catch(e){showToast('Copy unavailable')}}
document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.action,v=btn.dataset.value;if(a==='number')inputNumber(v);else if(a==='decimal')decimal();else if(a==='clear')clear();else if(a==='backspace')backspace();else if(a==='operator')setOperator(v);else if(a==='equals')calculate();else if(a==='percent')percent();else if(a==='sign')sign();else if(a==='function')scientific(v);else if(a==='constant')constant(v);else if(a==='parenthesis')parenthesis();else if(a==='memory')memoryAction(v);else if(a==='copy')copyResult()}));
historyEl.addEventListener('click',e=>{const item=e.target.closest('[data-history]');if(!item)return;const h=history[Number(item.dataset.history)];current=h.result;expression=h.expression;previous=null;operator=null;waiting=true;render()});$('clearHistory').onclick=()=>{history=[];save();render();showToast('History cleared')};$('settingsBtn').onclick=()=>settingsModal.classList.remove('hidden');$('closeSettings').onclick=()=>settingsModal.classList.add('hidden');settingsModal.addEventListener('click',e=>{if(e.target===settingsModal)settingsModal.classList.add('hidden')});
const scientificToggle=$('scientificToggle'),darkToggle=$('darkToggle'),hapticToggle=$('hapticToggle'),soundToggle=$('soundToggle'),autoCopyToggle=$('autoCopyToggle');scientificToggle.checked=settings.scientific;darkToggle.checked=settings.dark;hapticToggle.checked=settings.haptic;soundToggle.checked=settings.sound;autoCopyToggle.checked=settings.autoCopy;scientificEl.classList.toggle('hidden',!settings.scientific);document.body.classList.toggle('light',!settings.dark);$('angleBtn').textContent=angle;
scientificToggle.onchange=()=>{settings.scientific=scientificToggle.checked;scientificEl.classList.toggle('hidden',!settings.scientific);save()};darkToggle.onchange=()=>{settings.dark=darkToggle.checked;document.body.classList.toggle('light',!settings.dark);save()};hapticToggle.onchange=()=>{settings.haptic=hapticToggle.checked;save()};soundToggle.onchange=()=>{settings.sound=soundToggle.checked;save();beep()};autoCopyToggle.onchange=()=>{settings.autoCopy=autoCopyToggle.checked;save()};$('angleBtn').onclick=()=>{angle=angle==='DEG'?'RAD':'DEG';$('angleBtn').textContent=angle;save();showToast(`Angle mode: ${angle}`)};$('copyResult').onclick=copyResult;
$('forceUpdate').onclick=()=>{settingsModal.classList.add('hidden');showToast('Aither Calculator is up to date');setTimeout(()=>location.reload(),500)};
document.addEventListener('keydown',e=>{if(/^[0-9]$/.test(e.key))inputNumber(e.key);else if(e.key==='.')decimal();else if(e.key==='Enter'||e.key==='=')calculate();else if(['+','-','*','/','^'].includes(e.key))setOperator(e.key==='*'?'×':e.key==='/'?'÷':e.key==='-'?'−':e.key);else if(e.key==='Escape')clear();else if(e.key==='Backspace')backspace()});render();